# 1. Retriver 평가

### 1) 경로 설정

In [1]:
import sys
from pathlib import Path

# ✅ 노트북 위치가 어디든 프로젝트 루트를 찾아 sys.path에 추가
ROOT = Path.cwd()
while (ROOT / "src").exists() is False and ROOT.parent != ROOT:
    ROOT = ROOT.parent

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

print("ROOT =", ROOT)

ROOT = c:\Users\최무영\Desktop\코드잇 스프린트\Team2-RAG-Project

### 2) 평가 데이터셋 로드

In [78]:
import json

DATA_PATH = ROOT / "evaluation" / "test_questions.json"  # 본인 파일명으로
with open(DATA_PATH, "r", encoding="utf-8") as f:
    dataset = json.load(f)

len(dataset), dataset[0].keys()

(30, dict_keys(['id', 'document', 'question', 'answer', 'source_location']))

### 3) 평가용 retriever 함수

In [79]:
from src.retriever import rerank_docs

def retrieve_docs(question: str, k: int):
    # candidate_k는 rerank에 넣을 후보 수 (top_n보다 넉넉히)
    candidate_k = max(60, k * 3)
    return rerank_docs(
        question,
        top_n=k,                 # ✅ K개 반환
        candidate_k=candidate_k, # ✅ 후보는 넉넉히
        docid_scope_top_n=None,  # ✅ 평가에서는 필터 OFF
    )

### 4) Recall, MRR 계산 함수

In [80]:
import os, re
from typing import Any, List, Dict, Optional, Tuple

def _norm_fname(s: str) -> str:
    """basename + lower + 공백 정리"""
    if not s:
        return ""
    s = os.path.basename(str(s)).strip()
    s = re.sub(r"\s+", " ", s)
    return s.lower()

def _doc_fname(doc) -> str:
    md = getattr(doc, "metadata", None) or {}
    fn = md.get("file_name") or md.get("filename") or md.get("source") or md.get("path") or ""
    return _norm_fname(fn)

def _first_rank(docs: List[Any], gold_document: str, k: int) -> Optional[int]:
    """상위 k개에서 정답 문서가 최초 등장하는 rank(1-based). 없으면 None"""
    gold = _norm_fname(gold_document)
    for i, d in enumerate((docs or [])[:k], 1):
        if _doc_fname(d) == gold:
            return i
    return None

def recall_mrr_at_k(docs: List[Any], gold_document: str, k: int) -> Tuple[float, float]:
    r = _first_rank(docs, gold_document, k)
    if r is None:
        return 0.0, 0.0
    return 1.0, 1.0 / r

In [81]:
from typing import Callable

def evaluate_retrieval(
    dataset: List[Dict[str, Any]],
    retrieve_fn: Callable[[str, int], List[Any]],
    k_list: List[int] = [1, 3, 5, 10],
    debug_n: int = 0,   # 처음 N개만 검색 결과 출력 (0이면 미출력)
):
    n = len(dataset)
    recall_sum = {k: 0.0 for k in k_list}
    mrr_sum = {k: 0.0 for k in k_list}

    for idx, item in enumerate(dataset, 1):
        q = item["question"]
        gold_doc = item["document"]

        # ✅ 가장 큰 K로 한 번만 가져오고, 슬라이싱으로 재사용 (속도 개선)
        max_k = max(k_list)
        docs = retrieve_fn(q, max_k)

        for k in k_list:
            r, m = recall_mrr_at_k(docs, gold_doc, k)
            recall_sum[k] += r
            mrr_sum[k] += m

        if debug_n and idx <= debug_n:
            print(f"\n[DEBUG Q{idx:02d}] {q}")
            print("GOLD_DOC:", gold_doc)
            print("TOP docs:")
            for j, d in enumerate(docs[:min(5, len(docs))], 1):
                print(f"  {j}. {_doc_fname(d)}")

    results = {
        "n": n,
        "Recall": {k: recall_sum[k] / n for k in k_list},
        "MRR": {k: mrr_sum[k] / n for k in k_list},
    }
    return results

### 5) 기본 평가

In [82]:
import pandas as pd

k_list = [1, 3, 5, 10, 20]  # 보고 싶은 K로 조정 (단, rerank_docs top_n이 이만큼 나와야 함)

results = evaluate_retrieval(
    dataset=dataset,
    retrieve_fn=retrieve_docs,
    k_list=k_list,
    debug_n=2,  # 처음 2개만 디버그 출력
)

df = pd.DataFrame({
    "K": list(results["Recall"].keys()),
    "Recall@K": list(results["Recall"].values()),
    "MRR@K": list(results["MRR"].values()),
})
df

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

[DEBUG Q01] 이 사업의 예산(배정예산)은 총 얼마이며, 어떤 부서가 주관하나요?
GOLD_DOC: 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급).hwp
TOP docs:
  1. 국가철도공단_철도인프라 디지털트윈 정보화전략계획(isp) 수립 용역(변.hwp
  2. 경기도 안양시_호계체육관 배드민턴장 및 탁구장 예약시스템 구축 용역.hwp
  3. 한국철도공사 (용역)_모바일오피스 시스템 고도화 용역(총체 및 1차).hwp
  4. 경기도 안양시_호계체육관 배드민턴장 및 탁구장 예약시스템 구축 용역.hwp
  5. 수협중앙회_수협중앙회 수산물사이버직매장 시스템 재구축 ismp 수립 입.hwp

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

[DEBUG Q02] 사업 범위 중 '재난위험지역 경보발령 범위 확대'를 위해 사용되는 무선 통신 방식은?
GOLD_DOC: 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급).hwp
TOP docs:
  1. 경기도 안양시_호계체육관 배드민턴장 및 탁구장 예약시스템 구축 용역.hwp
  2. 경기도 안양시_호계체육관 배드민턴장 및 탁구장 예약시스템 구축 용역.hwp
  3. 한국철도공사 (용역)_[재공고][긴급][협상형]운행정보기록 자동분석시스.hwp
  4. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급).hwp
  5. 서울특별시 여성가족재단_(재공고, 협상) 서울 디지털성범죄 안심지원센.hwp

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

    K  Recall@K     MRR@K
0   1  0.066667  0.066667
1   3  0.066667  0.066667
2   5  0.133333  0.083333
3  10  0.200000  0.090000
4  20  0.266667  0.093627

# 2. BM25 / Dense(MMR) / Hybrid(RRF) / Rerank(FlashRank) 비교 평가

### 1) 경로 설정

In [83]:
import sys, importlib
from pathlib import Path

ROOT = Path.cwd()
while not (ROOT / "src").exists() and ROOT.parent != ROOT:
    ROOT = ROOT.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import src.retriever as retriever
importlib.reload(retriever)
print("retriever file:", retriever.__file__)

retriever file: c:\Users\최무영\Desktop\코드잇 스프린트\Team2-RAG-Project\src\retriever.py

### 2) 공통 유틸 + Recall/MRR 평가 함수

In [84]:
import os, re
from typing import Any, List, Dict, Optional, Tuple, Callable
import pandas as pd

def norm_fname(s: str) -> str:
    if not s:
        return ""
    s = os.path.basename(str(s)).strip()
    s = re.sub(r"\s+", " ", s)
    return s.lower()

def doc_fname(doc) -> str:
    md = getattr(doc, "metadata", None) or {}
    fn = md.get("file_name") or md.get("filename") or md.get("source") or md.get("path") or ""
    return norm_fname(fn)

def first_rank(docs: List[Any], gold_document: str, k: int) -> Optional[int]:
    gold = norm_fname(gold_document)
    for i, d in enumerate((docs or [])[:k], 1):
        if doc_fname(d) == gold:
            return i
    return None

def recall_mrr_at_k(docs: List[Any], gold_document: str, k: int) -> Tuple[float, float]:
    r = first_rank(docs, gold_document, k)
    if r is None:
        return 0.0, 0.0
    return 1.0, 1.0 / r

def evaluate_retrieval(
    dataset: List[Dict[str, Any]],
    retrieve_maxk_fn: Callable[[str, int], List[Any]],
    k_list: List[int] = [1, 3, 5, 10, 20],
    debug_n: int = 0,
    label: str = "",
):
    n = len(dataset)
    max_k = max(k_list)
    recall_sum = {k: 0.0 for k in k_list}
    mrr_sum = {k: 0.0 for k in k_list}

    for idx, item in enumerate(dataset, 1):
        q = item["question"]
        gold_doc = item["document"]

        docs = retrieve_maxk_fn(q, max_k) or []

        for k in k_list:
            r, m = recall_mrr_at_k(docs, gold_doc, k)
            recall_sum[k] += r
            mrr_sum[k] += m

        if debug_n and idx <= debug_n:
            print(f"\n[DEBUG:{label} Q{idx:02d}] {q}")
            print("GOLD_DOC:", gold_doc)
            print("TOP5:")
            for j, d in enumerate(docs[:5], 1):
                print(f"  {j}. {doc_fname(d)}")

    return {
        "n": n,
        "Recall": {k: recall_sum[k] / n for k in k_list},
        "MRR": {k: mrr_sum[k] / n for k in k_list},
    }

### 3) 단계별 retriever 함수

In [85]:
### BM25 ###
def retrieve_bm25(question: str, k: int):
    r = retriever.get_bm25_retriever()
    docs = r.invoke(question) or []
    return docs[:k]


### DENSE ###
def retrieve_dense(question: str, k: int):
    r = retriever.get_dense_retriever()
    docs = r.invoke(question) or []
    return docs[:k]


### Hybird ###
import inspect

_hsig = inspect.signature(retriever.get_hybrid_docs)
_hparams = _hsig.parameters

def retrieve_hybrid(question: str, k: int):
    if "k" in _hparams:
        docs = retriever.get_hybrid_docs(question, k=k) or []
        return docs[:k]
    docs = retriever.get_hybrid_docs(question) or []
    return docs[:k]


### Rerank ###
_rsig = inspect.signature(retriever.rerank_docs)
_rparams = _rsig.parameters

def retrieve_rerank(question: str, k: int):
    if "top_n" in _rparams:
        candidate_k = max(60, k * 3) if "candidate_k" in _rparams else None
        kwargs = {"top_n": k}
        if candidate_k is not None:
            kwargs["candidate_k"] = candidate_k
        if "docid_scope_top_n" in _rparams:
            kwargs["docid_scope_top_n"] = None  # 평가용: 필터 OFF
        return retriever.rerank_docs(question, **kwargs) or []
    docs = retriever.rerank_docs(question) or []
    return docs[:k]

### 4) 단계별 평가 및 비교

In [86]:
k_list = [1, 3, 5, 10, 20]   # 원하는 K

runs = [
    ("BM25",   retrieve_bm25),
    ("Dense",  retrieve_dense),
    ("Hybrid", retrieve_hybrid),
    ("Rerank", retrieve_rerank),
]

rows = []
for name, fn in runs:
    res = evaluate_retrieval(dataset, fn, k_list=k_list, debug_n=0, label=name)
    for k in k_list:
        rows.append({
            "Stage": name,
            "K": k,
            "Recall@K": res["Recall"][k],
            "MRR@K": res["MRR"][k],
        })

df = pd.DataFrame(rows).sort_values(["K", "Stage"])
df

[BM25] loaded docs=19387

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

     Stage   K  Recall@K     MRR@K
0     BM25   1  0.100000  0.100000
5    Dense   1  0.133333  0.133333
10  Hybrid   1  0.133333  0.133333
15  Rerank   1  0.066667  0.066667
1     BM25   3  0.133333  0.116667
6    Dense   3  0.166667  0.150000
11  Hybrid   3  0.200000  0.166667
16  Rerank   3  0.066667  0.066667
2     BM25   5  0.166667  0.125000
7    Dense   5  0.166667  0.150000
12  Hybrid   5  0.200000  0.166667
17  Rerank   5  0.133333  0.083333
3     BM25  10  0.166667  0.125000
8    Dense  10  0.166667  0.150000
13  Hybrid  10  0.233333  0.172222
18  Rerank  10  0.200000  0.090000
4     BM25  20  0.200000  0.128030
9    Dense  20  0.233333  0.153704
14  Hybrid  20  0.233333  0.172222
19  Rerank  20  0.266667  0.093627

In [90]:
pivot_recall = df.pivot(index="K", columns="Stage", values="Recall@K")
pivot_mrr    = df.pivot(index="K", columns="Stage", values="MRR@K")

**Recall**

In [94]:
pivot_recall

Stage      BM25     Dense    Hybrid    Rerank
K
1      0.100000  0.133333  0.133333  0.066667
3      0.133333  0.166667  0.200000  0.066667
5      0.166667  0.166667  0.200000  0.133333
10     0.166667  0.166667  0.233333  0.200000
20     0.200000  0.233333  0.233333  0.266667

**MRR**

In [92]:
pivot_mrr

Stage      BM25     Dense    Hybrid    Rerank
K
1      0.100000  0.133333  0.133333  0.066667
3      0.116667  0.150000  0.166667  0.066667
5      0.125000  0.150000  0.166667  0.083333
10     0.125000  0.150000  0.172222  0.090000
20     0.128030  0.153704  0.172222  0.093627

# 3. 평가 데이터셋 변경

### 1) 경로 설정

In [60]:
import sys, importlib
from pathlib import Path

ROOT = Path.cwd()
while not (ROOT / "src").exists() and ROOT.parent != ROOT:
    ROOT = ROOT.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import src.retriever as retriever
importlib.reload(retriever)
print("retriever file:", retriever.__file__)

retriever file: c:\Users\최무영\Desktop\코드잇 스프린트\Team2-RAG-Project\src\retriever.py

### 2) 수정된 평가 데이터셋

In [96]:
import json

DATA_PATH = ROOT / "evaluation" / "test_questions_2.json"  # 본인 파일명으로
with open(DATA_PATH, "r", encoding="utf-8") as f:
    dataset = json.load(f)

len(dataset), dataset[0].keys()

(30, dict_keys(['id', 'question', 'answer', 'evidence']))

### 3) 평가 함수

In [97]:
import os, re, unicodedata
from typing import Any, List, Dict, Optional, Tuple, Callable
import pandas as pd

def norm_doc_id(s: str) -> str:
    if not s:
        return ""
    s = unicodedata.normalize("NFC", str(s))
    s = os.path.basename(s).strip()
    s = re.sub(r"\.[A-Za-z0-9]+$", "", s)  # ✅ 확장자 제거
    s = re.sub(r"\s+", " ", s)
    return s.lower()

def gold_doc_ids_from_item(item):
    evs = item.get("evidence") or []
    out = []
    for ev in evs:
        f = ev.get("source_file")
        if f:
            did = norm_doc_id(f)
            if did not in out:
                out.append(did)
    return out

def doc_id_from_doc(doc):
    md = getattr(doc, "metadata", None) or {}
    fn = md.get("file_name") or md.get("filename") or md.get("source") or md.get("path") or ""
    return norm_doc_id(fn)


def first_rank_multi(docs: List[Any], gold_files: List[str], k: int) -> Optional[int]:
    """
    상위 k개 docs에서 gold_files 중 하나라도 최초 등장하는 rank(1-based)
    """
    gold_set = set(gold_files)
    for i, d in enumerate((docs or [])[:k], 1):
        if doc_id_from_doc(d) in gold_set:
            return i
    return None

def recall_mrr_at_k_multi(docs: List[Any], gold_files: List[str], k: int) -> Tuple[float, float]:
    r = first_rank_multi(docs, gold_files, k)
    if r is None:
        return 0.0, 0.0
    return 1.0, 1.0 / r

def evaluate_retrieval(
    dataset: List[Dict[str, Any]],
    retrieve_fn: Callable[[str, int], List[Any]],
    k_list: List[int] = [1, 3, 5, 10, 20],
    debug_n: int = 0,
    label: str = "",
):
    n = len(dataset)
    max_k = max(k_list)

    recall_sum = {k: 0.0 for k in k_list}
    mrr_sum = {k: 0.0 for k in k_list}

    for idx, item in enumerate(dataset, 1):
        q = item["question"]
        gold_files = gold_doc_ids_from_item(item)  # ✅ 이름 맞추기

        docs = retrieve_fn(q, max_k) or []

        for k in k_list:
            r, m = recall_mrr_at_k_multi(docs, gold_files, k)
            recall_sum[k] += r
            mrr_sum[k] += m

        if debug_n and idx <= debug_n:
            print(f"\n[DEBUG:{label} Q{idx:02d}] {q}")
            print("GOLD_DOC_IDS:")
            for gf in gold_files:
                print(" -", gf)
            print("TOP5:")
            for j, d in enumerate(docs[:5], 1):
                print(f"  {j}. {doc_id_from_doc(d)}")  # ✅ 평가 기준과 동일하게 출력

    return {
        "n": n,
        "Recall": {k: recall_sum[k] / n for k in k_list},
        "MRR": {k: mrr_sum[k] / n for k in k_list},
    }

### 4) 단계별 retriever 함수

In [ ]:
### BM25 ###
def retrieve_bm25(question: str, k: int):
    r = retriever.get_bm25_retriever()
    docs = r.invoke(question) or []
    return docs[:k]


### Dense ###
def retrieve_dense(question: str, k: int):
    r = retriever.get_dense_retriever()
    docs = r.invoke(question) or []
    return docs[:k]


### Hybird ###
import inspect

_hsig = inspect.signature(retriever.get_hybrid_docs)
_hparams = _hsig.parameters

def retrieve_hybrid(question: str, k: int):
    candidate_k = max(60, k * 3)

    # 신버전(get_hybrid_docs(question, k=...))이면 candidate_k를 넣기
    if "k" in _hparams:
        docs = retriever.get_hybrid_docs(question, k=candidate_k) or []
        return docs[:k]

    # 구버전이면 그냥 받아서 slice (구버전은 내부 k=60 고정일 확률 높음)
    docs = retriever.get_hybrid_docs(question) or []
    return docs[:k]


### Rerank ###
_rsig = inspect.signature(retriever.rerank_docs)
_rparams = _rsig.parameters

def retrieve_rerank(question: str, k: int):
    if "top_n" in _rparams:
        candidate_k = max(60, k * 3) if "candidate_k" in _rparams else None
        kwargs = {"top_n": k}
        if candidate_k is not None:
            kwargs["candidate_k"] = candidate_k
        if "docid_scope_top_n" in _rparams:
            kwargs["docid_scope_top_n"] = None  # 평가용: 필터 OFF
        return retriever.rerank_docs(question, **kwargs) or []
    docs = retriever.rerank_docs(question) or []
    return docs[:k]

### 5) 단계별 평가 및 비교

In [73]:
k_list = [1, 3, 5, 10, 20]
runs = [
    ("BM25",   retrieve_bm25),
    ("Dense",  retrieve_dense),
    ("Hybrid", retrieve_hybrid),
    ("Rerank", retrieve_rerank),
]

rows = []
for name, fn in runs:
    res = evaluate_retrieval(dataset, fn, k_list=k_list, debug_n=3, label=name)
    for k in k_list:
        rows.append({"Stage": name, "K": k, "Recall@K": res["Recall"][k], "MRR@K": res["MRR"][k]})

df = pd.DataFrame(rows).sort_values(["K", "Stage"])
df

[DEBUG:BM25 Q01] 봉화군에서 진행하는 재난 시스템 고도화 사업 예산이 총 얼마로 잡혀 있나요? 주관 부서가 어디인지도 확인 부탁드립니다.
GOLD_DOC_IDS:
 - 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
TOP5:
  1. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  2. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  3. 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축
  4. 서영대학교 산학협력단_전문대학 혁신지원사업 서영대학교 차세대 교육
  5. 국방과학연구소_대용량 자료전송시스템 고도화

[DEBUG:BM25 Q02] 이번 봉화군 재난위험지역 경보발령 사업에서 활용하는 무선 통신 방식은 구체적으로 무엇인가요?
GOLD_DOC_IDS:
 - 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
TOP5:
  1. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  2. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  3. 경기도 평택시_2024년도 평택시 버스정보시스템(bis) 구축사업
  4. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  5. 대검찰청_아태 사이버범죄 역량강화 허브(apc-hub) 홈페이지 및 온라인 교

[DEBUG:BM25 Q03] 봉화군 재난 사업용 하드웨어 규격 중에서 ECR-02 무선경보장치 스피커의 출력 기준을 알려주세요.
GOLD_DOC_IDS:
 - 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
TOP5:
  1. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  2. 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축
  3. 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축
  4. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  5. 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

[DEBUG:Dense Q01] 봉화군에서 진행하는 재난 시스템 고도화 사업 예산이 총 얼마로 잡혀 있나요? 주관 부서가 어디인지도 확인 부탁드립니다.
GOLD_DOC_IDS:
 - 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
TOP5:
  1. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  2. 국가철도공단_철도인프라 디지털트윈 정보화전략계획(isp) 수립 용역(변
  3. 광주과학기술원_실시간통합연구비관리시스템(rcms) 연계 모듈 변경 사업
  4. 한국사학진흥재단_대학재정정보시스템(기본재산 및 기채 사후관리) 고
  5. 인천광역시 동구_수도국산달동네박물관 전시해설 시스템 구축(협상에

[DEBUG:Dense Q02] 이번 봉화군 재난위험지역 경보발령 사업에서 활용하는 무선 통신 방식은 구체적으로 무엇인가요?
GOLD_DOC_IDS:
 - 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
TOP5:
  1. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  2. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  3. (사）한국대학스포츠협의회_kusf 체육특기자 경기기록 관리시스템 개발
  4. koica 전자조달_[긴급] [지문] [국제] 우즈베키스탄 열린 의정활동 상하원
  5. 국가철도공단_철도인프라 디지털트윈 정보화전략계획(isp) 수립 용역(변

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

[DEBUG:Dense Q03] 봉화군 재난 사업용 하드웨어 규격 중에서 ECR-02 무선경보장치 스피커의 출력 기준을 알려주세요.
GOLD_DOC_IDS:
 - 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
TOP5:
  1. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  2. 한국수자원조사기술원_수문자료정보관리시스템(hdims) 재구축 용역(3단계
  3. 서울특별시 여성가족재단_(재공고, 협상) 서울 디지털성범죄 안심지원센
  4. 인천공항운영서비스(주)_인천공항운영서비스㈜ 차세대 erp시스템 구축
  5. 축산물품질평가원_축산물이력관리시스템 개선(정보화 사업)

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

[DEBUG:Hybrid Q01] 봉화군에서 진행하는 재난 시스템 고도화 사업 예산이 총 얼마로 잡혀 있나요? 주관 부서가 어디인지도 확인 부탁드립니다.
GOLD_DOC_IDS:
 - 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
TOP5:
  1. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  2. 대한상공회의소_기업 재생에너지 지원센터 홈페이지 개편 및 시스템 고
  3. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  4. 고려대학교_차세대 포털·학사 정보시스템 구축사업
  5. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

[DEBUG:Hybrid Q02] 이번 봉화군 재난위험지역 경보발령 사업에서 활용하는 무선 통신 방식은 구체적으로 무엇인가요?
GOLD_DOC_IDS:
 - 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
TOP5:
  1. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  2. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  3. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  4. 울산광역시_2024년 버스정보시스템 확대 구축 및 기능개선 용역
  5. 한국전기안전공사_전기안전 관제시스템 보안 모듈 개발 용역

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

[DEBUG:Hybrid Q03] 봉화군 재난 사업용 하드웨어 규격 중에서 ECR-02 무선경보장치 스피커의 출력 기준을 알려주세요.
GOLD_DOC_IDS:
 - 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
TOP5:
  1. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  2. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  3. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  4. 한국철도공사 (용역)_[재공고][긴급][협상형]운행정보기록 자동분석시스
  5. 국립중앙의료원_(긴급)「2024년도 차세대 응급의료 상황관리시스템 구축

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

[DEBUG:Rerank Q01] 봉화군에서 진행하는 재난 시스템 고도화 사업 예산이 총 얼마로 잡혀 있나요? 주관 부서가 어디인지도 확인 부탁드립니다.
GOLD_DOC_IDS:
 - 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
TOP5:
  1. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  2. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  3. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  4. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  5. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

[DEBUG:Rerank Q02] 이번 봉화군 재난위험지역 경보발령 사업에서 활용하는 무선 통신 방식은 구체적으로 무엇인가요?
GOLD_DOC_IDS:
 - 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
TOP5:
  1. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  2. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  3. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  4. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  5. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)

[DEBUG:Rerank Q03] 봉화군 재난 사업용 하드웨어 규격 중에서 ECR-02 무선경보장치 스피커의 출력 기준을 알려주세요.
GOLD_DOC_IDS:
 - 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
TOP5:
  1. 파주도시관광공사_종량제봉투 판매관리 전산시스템 개선사업
  2. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  3. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  4. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)
  5. 경상북도 봉화군_봉화군 재난통합관리시스템 고도화 사업(협상)(긴급)

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

     Stage   K  Recall@K     MRR@K
0     BM25   1  0.500000  0.500000
5    Dense   1  0.533333  0.533333
10  Hybrid   1  0.566667  0.566667
15  Rerank   1  0.433333  0.433333
1     BM25   3  0.566667  0.533333
6    Dense   3  0.733333  0.622222
11  Hybrid   3  0.700000  0.627778
16  Rerank   3  0.633333  0.527778
2     BM25   5  0.600000  0.541667
7    Dense   5  0.733333  0.622222
12  Hybrid   5  0.866667  0.664444
17  Rerank   5  0.766667  0.557778
3     BM25  10  0.700000  0.553704
8    Dense  10  0.833333  0.636706
13  Hybrid  10  0.900000  0.668611
18  Rerank  10  0.800000  0.561111
4     BM25  20  0.766667  0.557934
9    Dense  20  0.900000  0.640750
14  Hybrid  20  0.933333  0.670278
19  Rerank  20  0.933333  0.570438

In [74]:
pivot_recall = df.pivot(index="K", columns="Stage", values="Recall@K")
pivot_mrr    = df.pivot(index="K", columns="Stage", values="MRR@K")

**Recall**

In [75]:
pivot_recall

Stage      BM25     Dense    Hybrid    Rerank
K
1      0.500000  0.533333  0.566667  0.433333
3      0.566667  0.733333  0.700000  0.633333
5      0.600000  0.733333  0.866667  0.766667
10     0.700000  0.833333  0.900000  0.800000
20     0.766667  0.900000  0.933333  0.933333

**MRR**

In [76]:
pivot_mrr

Stage      BM25     Dense    Hybrid    Rerank
K
1      0.500000  0.533333  0.566667  0.433333
3      0.533333  0.622222  0.627778  0.527778
5      0.541667  0.622222  0.664444  0.557778
10     0.553704  0.636706  0.668611  0.561111
20     0.557934  0.640750  0.670278  0.570438

# 4. 평가 데이터셋 활용하여 generator 평가

### 1) 환경 설정

In [10]:
import os, sys
from pathlib import Path
from dotenv import load_dotenv

# 1) 노트북 위치가 어디든 프로젝트 루트 탐색 (src 폴더 기준)
ROOT = Path.cwd().resolve()
while not (ROOT / "src").exists() and ROOT.parent != ROOT:
    ROOT = ROOT.parent

assert (ROOT / "src").exists(), f"프로젝트 루트를 못 찾았습니다. 시작 cwd={Path.cwd()}"

# 2) 상대경로/로더 안정화: cwd를 루트로 이동
os.chdir(ROOT)

# 3) import 안정화: 루트를 sys.path 최상단에 1회만 추가
root_str = str(ROOT)
if root_str not in sys.path:
    sys.path.insert(0, root_str)

# 4) .env 로드
load_dotenv(ROOT / ".env")

print("cwd:", Path.cwd())
print("ROOT:", ROOT)
print("ROOT in sys.path:", root_str in sys.path)
print("OPENAI_API_KEY exists?:", bool(os.getenv("OPENAI_API_KEY")))

cwd: C:\Users\최무영\Desktop\코드잇 스프린트\Team2-RAG-Project
ROOT: C:\Users\최무영\Desktop\코드잇 스프린트\Team2-RAG-Project
ROOT in sys.path: True
OPENAI_API_KEY exists?: True

In [12]:
EVAL_PY = ROOT / "evaluation" / "evaluate.py"
DATASET = ROOT / "evaluation" / "test_questions_2.json"

assert EVAL_PY.exists(), f"evaluate.py 없음: {EVAL_PY}"
assert DATASET.exists(), f"test_questions_2.json 없음: {DATASET}"

print("EVAL_PY:", EVAL_PY)
print("DATASET:", DATASET)

EVAL_PY: C:\Users\최무영\Desktop\코드잇 스프린트\Team2-RAG-Project\evaluation\evaluate.py
DATASET: C:\Users\최무영\Desktop\코드잇 스프린트\Team2-RAG-Project\evaluation\test_questions_2.json

### 2) generator 체인 생성

In [13]:
from src.generator import get_rag_chain

chain = get_rag_chain()

# (선택) 스모크 테스트
print(chain.invoke("남서울대 학사행정 암호화 사업 추진 배경에 언급된 기존 시스템의 주요 보안 취약점은 무엇인가요?")[:300])
# print(ask(chain, "남서울대 학사행정 암호화 사업 추진 배경에 언급된 기존 시스템의 주요 보안 취약점은 무엇인가요?"))

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

ANSWER: 기존에 파일 암호화가 도입되어 있지 않아 원본 첨부파일 유출 시 개인정보가 그대로 노출될 위험이 있으며, 웹방화벽·서버 IP 정책 등 외부 접근 통제는 존재하나 보안사고 특성상 100% 안전하지 않음

SOURCES:
- file_name=남서울대학교_[혁신-국고] 남서울대학교 스마트 정보시스템 활성화(학사.hwp | doc_id=남서울대학교_[혁신-국고] 남서울대학교 스마트 정보시스템 활성화(학사 | chunk=4 | source_type=hwp_chunk_md
- file_name=남서울대학교_[혁신-국고] 남서울

### 3) 평가 실행 (soft_score)기반

In [14]:
from evaluation.evaluate import run_evaluation

results = run_evaluation(
    chain=chain,
    dataset_path=str(DATASET),
    threshold=0.35,
    use_langfuse=False,
    pred_preview_chars=300,
    retriever=None,   # LLM judge까지 쓰려면 아래 5) 참고
)

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

RAG 시스템 평가 시작...

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q01 =================
Q: 봉화군에서 진행하는 재난 시스템 고도화 사업 예산이 총 얼마로 잡혀 있나요? 주관 부서가 어디인지도 확인 부탁드립니다.
GOLD: 900,000,000원(VAT 포함)이며, 봉화군 안전건설과에서 주관합니다.

--- PRED_CORE(300) ---
사업금액: 900,000,000원(부가세 포함). 주관부서: 근거 문서에서 확인할 수 없습니다

Q01: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q02 =================
Q: 이번 봉화군 재난위험지역 경보발령 사업에서 활용하는 무선 통신 방식은 구체적으로 무엇인가요?
GOLD: LTE 및 DMB(EWS) 방식을 활용합니다.

--- PRED_CORE(300) ---
LTE 및 DMB(EWS) 기반의 무선방식

Q02: [O]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

================= DEBUG Q03 =================
Q: 봉화군 재난 사업용 하드웨어 규격 중에서 ECR-02 무선경보장치 스피커의 출력 기준을 알려주세요.
GOLD: 100W 이상의 출력을 지원해야 합니다.

--- PRED_CORE(300) ---
앰프출력 : 최대 400W 이상(100Wx4ch)

Q03: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q04 =================
Q: 고려대 차세대 학사시스템 구축 사업의 전체 예산 규모와 연도별 분할 지급 비율이 어떻게 되나요?
GOLD: 총 11,270,000,000원이며, 2024년 30%, 2025년 40%, 2026년 30%를 지급합니다.

--- PRED_CORE(300) ---
전체 예산 11,270,000,000원(부가가치세 포함). 연도별 분할 지급 비율은 2024학년도 약 30%, 2025학년도 약 40%, 2026학년도 약 30%.

Q04: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q05 =================
Q: 고려대 포털 고도화 작업 중에 기존 'AI선배' 서비스의 아키텍처는 어떤 방향으로 재설계될 예정인가요?
GOLD: Python 기반 모델 아키텍처 고도화 및 서비스 통합 재설계입니다.

--- PRED_CORE(300) ---
- 원데이터 추출·적재방식 및 데이터마트 생성방식을 경영통계시스템과 일원화
- Python으로 구현된 모델의 연속실행 및 병렬실행 아키텍처 고도화
- AI선배, 포털서비스, 챗봇서비스를 통합해 추천·통계 데이터 제공 기능 재설계

Q05: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q06 =================
Q: 고려대 학사행정시스템을 구축할 때 서울과 세종 캠퍼스별 처리에 대한 별도의 지침이 있을까요?
GOLD: 표준화된 시스템 구축을 원칙으로 하되, 업무 성격상 캠퍼스 구분이 필요한 경우 이를 반영하여 구현합니다.

--- PRED_CORE(300) ---
네. 표준화된 통합 학사행정시스템을 구축하되, 조회/입력 등 기능 처리 시 서울캠퍼스와 세종캠퍼스 구분 처리가 필요한 경우에는 구분해서 처리할 수 있도록 구현해야 합니다. 또한 강의계획서 등 일부 학사 기능은 캠퍼스별 차이를 반영하도록 요구됩니다.

Q06: [O]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q07 =================
Q: 중앙의료원 응급의료 상황관리시스템 구축 사업에서 광역상황실이 신규로 설치되는 4개 지역은 어디인가요?
GOLD: 서울, 대전, 대구, 광주 지역입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q07: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

================= DEBUG Q08 =================
Q: 국립중앙의료원 인프라 요건 중 DB 서버(Server-001)가 갖추어야 할 최소 CPU 코어 사양을 알려주세요.
GOLD: 16 Cores 이상을 요구합니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q08: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q09 =================
Q: 응급환자 전원 지원 시스템의 핵심 업무 중 '상황의사'는 주로 어떤 역할을 수행하게 되나요?
GOLD: 의뢰 대상 기관 선정, 수용 의뢰 및 상황 지원을 담당합니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q09: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q10 =================
Q: 나노종합기술원의 스마트 팹 설비온라인 시스템 구축 용역은 계약 후 기간이 총 얼마나 소요되나요?
GOLD: 총 18개월입니다.

--- PRED_CORE(300) ---
계약체결일로부터 18개월

Q10: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q11 =================
Q: 기술원의 'LoT Tracking' 환경 구축을 위해서 구체적으로 어떤 장치나 인터페이스 작업이 진행되나요?
GOLD: Carrier ID 인식 장치 설치 및 정보 표시 인터페이스 구축입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q11: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q12 =================
Q: 나노종합기술원 보안 요건 중에서 DB 암호화 제품이 반드시 획득해야 하는 인증이 무엇인가요?
GOLD: CC인증(공통평가기준)이 필수입니다.

--- PRED_CORE(300) ---
검증필 암호모듈 탑재(암호모듈 검증필)

Q12: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

================= DEBUG Q13 =================
Q: 아시아물위원회에서 추진하는 우즈벡-키르기스스탄 기후대응 관개시스템 사업의 구체적인 수혜 지역이 어디인가요?
GOLD: 키르기즈스탄(Talas-Alatau)과 우즈베키스탄(Ferghana)입니다.

--- PRED_CORE(300) ---
키르기스스탄: Talas‑Alatau 및 Ferghana 산맥, 우즈베키스탄: Ferghana

Q13: [O]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q14 =================
Q: 우즈벡 스마트 관개사업 전문가 파견 시, '수자원 전문가'에게 요구되는 최소 기술 등급 자격은 무엇인가요?
GOLD: 특급 기술자 또는 기술사 자격이 필요합니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q14: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q15 =================
Q: 우즈벡-키르기스스탄 현지 지원용 기자재 목록에 포함된 이동 수단은 구체적으로 어떤 차량인가요?
GOLD: SUV 차량 1대입니다.

--- PRED_CORE(300) ---
차량 : SUV 1대

Q15: [O]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q16 =================
Q: 어촌어항공단 차세대 경영관리시스템 사업에서 그룹웨어(GW)의 주요 개선 목표가 무엇인가요?
GOLD: 사용자 중심의 UI/UX 개선 및 모바일 서비스 강화입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q16: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q17 =================
Q: 공단 사업 지침상 개인정보 보호법을 위반할 경우 매출액 대비 과징금 부과기준율은 어떻게 되나요?
GOLD: 위반 관련 매출액의 1,000분의 21(2.1%)입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q17: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

================= DEBUG Q18 =================
Q: 한국어촌어항공단 사업 수행 인력들의 보안을 위한 비밀유지 서약서는 어느 시점에 제출해야 하나요?
GOLD: 착수계 제출 시 함께 제출해야 합니다.

--- PRED_CORE(300) ---
최종낙찰자 제출

Q18: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q19 =================
Q: 인천해양박물관 시스템에서 관리하게 될 '해양자료'의 세부 범주에는 어떤 것들이 포함되나요?
GOLD: 유물, 도서, 기록물 등 박물관 보유 자료 전체입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q19: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q20 =================
Q: 박물관 시스템 보안 약점 중 'Null Pointer 역참조'는 어떤 카테고리로 분류되어 관리되나요?
GOLD: 코드 오류 항목에 해당합니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q20: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q21 =================
Q: 인천해양박물관 해양자료관리시스템의 구축 완료 후 하자담보 책임기간은 몇 년인가요?
GOLD: 1년입니다.

--- PRED_CORE(300) ---
검사(검수) 완료 후 1년(12개월)

Q21: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q22 =================
Q: 벤처확인시스템 고도화 과정에서 '복수의결권주식' 제도를 도입하려는 목적이 무엇인지 알려주세요.
GOLD: 비상장 벤처기업 창업자의 경영권 침해 없이 대규모 투자 유치를 지원하기 위함입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q22: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q23 =================
Q: 벤처확인시스템 보안 요구사항 중 SQL 인젝션이나 XSS 방지를 위한 입력 데이터 검증 기준은 무엇인가요?
GOLD: SQL 인젝션, 크로스사이트 스크립팅(XSS) 방지 등을 위한 필터링 적용입니다.

--- PRED_CORE(300) ---
프로그램 입력값에 대한 검증 누락 또는 부적절한 검증을 금지(입력데이터 검증 및 표현 기준)하고, 관리자 및 사용자 페이지에 SQL인젝션·크로스사이트스크립팅(XSS) 등 웹 취약점이 없어야 하며(오픈소스·외부라이브러리 사용 시 취약점 검사로 증빙해야 함)

Q23: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q24 =================
Q: 벤처확인종합관리시스템 제안서 평가 항목 중 '수행 조직' 파트에 배정된 배점은 몇 점인가요?
GOLD: 10점입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q24: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q25 =================
Q: 남서울대 학사행정 암호화 사업 추진 배경에 언급된 기존 시스템의 주요 보안 취약점은 무엇인가요?
GOLD: 주요 개인정보가 평문으로 저장되어 있어 유출 시 심각한 위협이 됨을 명시하고 있습니다.

--- PRED_CORE(300) ---
기존 시스템에 파일 암호화가 도입되어 있지 않아 원본 첨부파일 유출 시 개인정보 노출 및 대형 사고로 이어질 위험이 있으며, 웹방화벽·서버 IP 정책 등으로 외부 접근을 관리하나 보안사고 특성상 100% 안전하지 않음

Q25: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q26 =================
Q: 남서울대 스마트 정보시스템 사업 완료 후 산출되는 결과물들의 지식재산권은 어디에 귀속되나요?
GOLD: 남서울대학교에 귀속됩니다.

--- PRED_CORE(300) ---
남서울대학교에 귀속됩니다.

Q26: [O]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q27 =================
Q: 남서울대 시스템 활성화 사업 수행 시, 투입 인력들의 대학 내 장소 상주 조건은 어떻게 규정되어 있나요?
GOLD: 사업의 효율적 추진을 위해 대학 내 지정된 장소에 상주함을 원칙으로 합니다.

--- PRED_CORE(300) ---
투입 인력은 남서울대학교 출입 시 반드시 허가된 지역만 출입해야 하며, 남서울대학교 정보보안 관리규정 준수·정기 보안감사에 협조해야 하고, 핵심 정보시스템 또는 기밀 정보를 다루는 경우 물리적·논리적(예: E-mail 모니터링) 모니터링 대상이 될 수 있으며, 내부 시스템 사용 권한을 부여받은 경우 계정·패스워드 노출에 각별히 주의해야 합니다

Q27: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q28 =================
Q: 꿀 등급 판정을 수행하는 현장 인력을 위해 이번에 새롭게 고도화되는 모바일 기능은 무엇인가요?
GOLD: 태블릿 PC 기반의 모바일 등급판정 시스템 고도화입니다.

--- PRED_CORE(300) ---
품질평가사가 시료채취 후 드럼봉인 시 봉인기에 각인된 드럼관리번호를 관리하기 위한 기능 고도화

Q28: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q29 =================
Q: 꿀 품질평가 사업 보안 지침상 '경미한 위반 3건' 이상 발생 시 어떤 등급의 위약금을 물게 되나요?
GOLD: D급(200만 원 이하 위약금)입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q29: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

================= DEBUG Q30 =================
Q: 꿀 품질관리 시스템 누출금지 대상정보 중에서 2번 항목에 해당하는 구체적인 정보는 무엇인가요?
GOLD: 누출금지 대상정보 2번 항목입니다.(세부 정보시스템 구성현황 및 정보통신망 구성도)

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q30: [X]

평가 완료: 5 / 30

### 4) LLM-as-a-judge 평가

In [15]:
from src.generator import get_db_cached
from evaluation.evaluate import run_evaluation

db = get_db_cached()
retriever = db.as_retriever(search_kwargs={"k": 6})

results_llm_as_a_judge = run_evaluation(
    chain=chain,
    dataset_path=str(DATASET),
    threshold=0.35,
    retriever=retriever,  # ✅ llm_judge_score 활성화
)

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

RAG 시스템 평가 시작...

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q01 =================
Q: 봉화군에서 진행하는 재난 시스템 고도화 사업 예산이 총 얼마로 잡혀 있나요? 주관 부서가 어디인지도 확인 부탁드립니다.
GOLD: 900,000,000원(VAT 포함)이며, 봉화군 안전건설과에서 주관합니다.

--- PRED_CORE(300) ---
사업금액: 900,000,000원(부가세 포함)
주관 부서: 근거 문서에서 확인할 수 없습니다

Q01: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q02 =================
Q: 이번 봉화군 재난위험지역 경보발령 사업에서 활용하는 무선 통신 방식은 구체적으로 무엇인가요?
GOLD: LTE 및 DMB(EWS) 방식을 활용합니다.

--- PRED_CORE(300) ---
LTE 및 DMB(EWS) 기반 무선방식 (세부: LTE Cat 1, BAND 1/3/5; DMB모듈 2Ch, T‑DMB)

Q02: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q03 =================
Q: 봉화군 재난 사업용 하드웨어 규격 중에서 ECR-02 무선경보장치 스피커의 출력 기준을 알려주세요.
GOLD: 100W 이상의 출력을 지원해야 합니다.

--- PRED_CORE(300) ---
앰프출력: 최대 400W 이상(100W x 4ch). 또한 혼스피커는 8Ω/75W 이상, PA(컬럼) 스피커는 8Ω/20W 이상.

Q03: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q04 =================
Q: 고려대 차세대 학사시스템 구축 사업의 전체 예산 규모와 연도별 분할 지급 비율이 어떻게 되나요?
GOLD: 총 11,270,000,000원이며, 2024년 30%, 2025년 40%, 2026년 30%를 지급합니다.

--- PRED_CORE(300) ---
총 예산 11,270,000,000원(V.A.T 포함). 3년 분할지급: 2024학년도 약 30%, 2025학년도 약 40%, 2026학년도 약 30%.

Q04: [O]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q05 =================
Q: 고려대 포털 고도화 작업 중에 기존 'AI선배' 서비스의 아키텍처는 어떤 방향으로 재설계될 예정인가요?
GOLD: Python 기반 모델 아키텍처 고도화 및 서비스 통합 재설계입니다.

--- PRED_CORE(300) ---
기존 AI선배는
- 경영통계시스템과 원데이터 추출·적재방식 및 데이터마트 생성방식 일원화,
- Python으로 구현한 모델의 연속실행 및 병렬실행 아키첵처 고도화,
- AI선배·포털서비스·챗봇서비스 통합을 통한 추천·통계 데이터 제공 기능 재설계
방향으로 재설계될 예정입니다.

Q05: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q06 =================
Q: 고려대 학사행정시스템을 구축할 때 서울과 세종 캠퍼스별 처리에 대한 별도의 지침이 있을까요?
GOLD: 표준화된 시스템 구축을 원칙으로 하되, 업무 성격상 캠퍼스 구분이 필요한 경우 이를 반영하여 구현합니다.

--- PRED_CORE(300) ---
예. 표준화된 통합 학사행정시스템으로 구현하되, 조회/입력 등 기능 처리 시 서울캠퍼스와 세종캠퍼스 구분 처리가 필요한 경우 구분해서 처리할 수 있도록 구현해야 하며, 캠퍼스별 역량관리체계 및 캠퍼스별 교과목별 강의시간(60분, 75분 등) 유연관리 기능 등 캠퍼스별 차이를 반영하는 기능 구현 요구가 있습니다.

Q06: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q07 =================
Q: 중앙의료원 응급의료 상황관리시스템 구축 사업에서 광역상황실이 신규로 설치되는 4개 지역은 어디인가요?
GOLD: 서울, 대전, 대구, 광주 지역입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q07: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"

================= DEBUG Q08 =================
Q: 국립중앙의료원 인프라 요건 중 DB 서버(Server-001)가 갖추어야 할 최소 CPU 코어 사양을 알려주세요.
GOLD: 16 Cores 이상을 요구합니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q08: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q09 =================
Q: 응급환자 전원 지원 시스템의 핵심 업무 중 '상황의사'는 주로 어떤 역할을 수행하게 되나요?
GOLD: 의뢰 대상 기관 선정, 수용 의뢰 및 상황 지원을 담당합니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q09: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q10 =================
Q: 나노종합기술원의 스마트 팹 설비온라인 시스템 구축 용역은 계약 후 기간이 총 얼마나 소요되나요?
GOLD: 총 18개월입니다.

--- PRED_CORE(300) ---
계약체결일로부터 18개월

Q10: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q11 =================
Q: 기술원의 'LoT Tracking' 환경 구축을 위해서 구체적으로 어떤 장치나 인터페이스 작업이 진행되나요?
GOLD: Carrier ID 인식 장치 설치 및 정보 표시 인터페이스 구축입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q11: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q12 =================
Q: 나노종합기술원 보안 요건 중에서 DB 암호화 제품이 반드시 획득해야 하는 인증이 무엇인가요?
GOLD: CC인증(공통평가기준)이 필수입니다.

--- PRED_CORE(300) ---
검증필 암호모듈 탑재

Q12: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q13 =================
Q: 아시아물위원회에서 추진하는 우즈벡-키르기스스탄 기후대응 관개시스템 사업의 구체적인 수혜 지역이 어디인가요?
GOLD: 키르기즈스탄(Talas-Alatau)과 우즈베키스탄(Ferghana)입니다.

--- PRED_CORE(300) ---
키르기스스탄(Talas-Alatau 및 Ferghana 산맥), 우즈베키스탄(Ferghana)

Q13: [O]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q14 =================
Q: 우즈벡 스마트 관개사업 전문가 파견 시, '수자원 전문가'에게 요구되는 최소 기술 등급 자격은 무엇인가요?
GOLD: 특급 기술자 또는 기술사 자격이 필요합니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q14: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q15 =================
Q: 우즈벡-키르기스스탄 현지 지원용 기자재 목록에 포함된 이동 수단은 구체적으로 어떤 차량인가요?
GOLD: SUV 차량 1대입니다.

--- PRED_CORE(300) ---
SUV 1대

Q15: [O]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q16 =================
Q: 어촌어항공단 차세대 경영관리시스템 사업에서 그룹웨어(GW)의 주요 개선 목표가 무엇인가요?
GOLD: 사용자 중심의 UI/UX 개선 및 모바일 서비스 강화입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q16: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q17 =================
Q: 공단 사업 지침상 개인정보 보호법을 위반할 경우 매출액 대비 과징금 부과기준율은 어떻게 되나요?
GOLD: 위반 관련 매출액의 1,000분의 21(2.1%)입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q17: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q18 =================
Q: 한국어촌어항공단 사업 수행 인력들의 보안을 위한 비밀유지 서약서는 어느 시점에 제출해야 하나요?
GOLD: 착수계 제출 시 함께 제출해야 합니다.

--- PRED_CORE(300) ---
사업 착수 시 제출해야 합니다.

Q18: [O]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q19 =================
Q: 인천해양박물관 시스템에서 관리하게 될 '해양자료'의 세부 범주에는 어떤 것들이 포함되나요?
GOLD: 유물, 도서, 기록물 등 박물관 보유 자료 전체입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q19: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q20 =================
Q: 박물관 시스템 보안 약점 중 'Null Pointer 역참조'는 어떤 카테고리로 분류되어 관리되나요?
GOLD: 코드 오류 항목에 해당합니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q20: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q21 =================
Q: 인천해양박물관 해양자료관리시스템의 구축 완료 후 하자담보 책임기간은 몇 년인가요?
GOLD: 1년입니다.

--- PRED_CORE(300) ---
1년(검수완료일로부터 12개월)

Q21: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"

================= DEBUG Q22 =================
Q: 벤처확인시스템 고도화 과정에서 '복수의결권주식' 제도를 도입하려는 목적이 무엇인지 알려주세요.
GOLD: 비상장 벤처기업 창업자의 경영권 침해 없이 대규모 투자 유치를 지원하기 위함입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q22: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q23 =================
Q: 벤처확인시스템 보안 요구사항 중 SQL 인젝션이나 XSS 방지를 위한 입력 데이터 검증 기준은 무엇인가요?
GOLD: SQL 인젝션, 크로스사이트 스크립팅(XSS) 방지 등을 위한 필터링 적용입니다.

--- PRED_CORE(300) ---
입력데이터 검증은 "입력값에 대한 검증 누락 또는 부적절한 검증, 데이터의 잘못된 형식지정"으로 인한 보안약점이 발생하지 않도록 구현해야 하며(소프트웨어 보안약점 기준의 '입력데이터 검증 및 표현'), 관련 정보보호 처리기준은 국가정보원 기준 및 중소벤처기업부·벤처기업확인기관 관련 지침을 준용해야 합니다.

Q23: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q24 =================
Q: 벤처확인종합관리시스템 제안서 평가 항목 중 '수행 조직' 파트에 배정된 배점은 몇 점인가요?
GOLD: 10점입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q24: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"

================= DEBUG Q25 =================
Q: 남서울대 학사행정 암호화 사업 추진 배경에 언급된 기존 시스템의 주요 보안 취약점은 무엇인가요?
GOLD: 주요 개인정보가 평문으로 저장되어 있어 유출 시 심각한 위협이 됨을 명시하고 있습니다.

--- PRED_CORE(300) ---
기존에 파일 암호화가 도입되어 있지 않아 원본 파일 유출 시 개인정보가 노출되어 큰 사고로 이어질 위험이 크고, 웹방화벽·서버 IP 정책 등 일부 접근통제는 있으나 “100% 안전한 시스템은 존재하지 않음”으로 외부 접근·보안사고에 취약함

Q25: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q26 =================
Q: 남서울대 스마트 정보시스템 사업 완료 후 산출되는 결과물들의 지식재산권은 어디에 귀속되나요?
GOLD: 남서울대학교에 귀속됩니다.

--- PRED_CORE(300) ---
남서울대학교에 귀속됩니다. (사업수행 중 산출된 서적, 컴퓨터 프로그램, 장치, 기타 문서 등의 권리는 남서울대학교에 귀속)

Q26: [O]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q27 =================
Q: 남서울대 시스템 활성화 사업 수행 시, 투입 인력들의 대학 내 장소 상주 조건은 어떻게 규정되어 있나요?
GOLD: 사업의 효율적 추진을 위해 대학 내 지정된 장소에 상주함을 원칙으로 합니다.

--- PRED_CORE(300) ---
투입 인력은 남서울대학교 출입 시 반드시 허가된 지역만 출입해야 하며(보안관리 규정 준수), 내부 시스템 사용 권한을 부여받은 경우 계정·패스워드 노출에 각별히 주의해야 합니다. 또한 핵심 정보시스템 또는 기밀 정보를 다루는 직원에 대해서는 E-mail 모니터링 등 물리적·논리적 모니터링이 이루어질 수 있습니다.

Q27: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"

================= DEBUG Q28 =================
Q: 꿀 등급 판정을 수행하는 현장 인력을 위해 이번에 새롭게 고도화되는 모바일 기능은 무엇인가요?
GOLD: 태블릿 PC 기반의 모바일 등급판정 시스템 고도화입니다.

--- PRED_CORE(300) ---
품질평가사가 시료채취 후 드럼봉인 시 봉인기에 각인된 드럼관리번호를 관리하는 기능 구현(아울러 QR코드 연계 URL 및 앱에서 등급판정 확인서 열람 등 소비자용 앱 조회기능도 고도화)

Q28: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

================= DEBUG Q29 =================
Q: 꿀 품질평가 사업 보안 지침상 '경미한 위반 3건' 이상 발생 시 어떤 등급의 위약금을 물게 되나요?
GOLD: D급(200만 원 이하 위약금)입니다.

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q29: [X]

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 403 Forbidden"

================= DEBUG Q30 =================
Q: 꿀 품질관리 시스템 누출금지 대상정보 중에서 2번 항목에 해당하는 구체적인 정보는 무엇인가요?
GOLD: 누출금지 대상정보 2번 항목입니다.(세부 정보시스템 구성현황 및 정보통신망 구성도)

--- PRED_CORE(300) ---
근거 문서에서 확인할 수 없습니다

Q30: [X]

평가 완료: 5 / 30

In [20]:
import pandas as pd

df = pd.DataFrame(results)
df_llm_judge = pd.DataFrame(results_llm_as_a_judge)
#display(df[["id","correct","score","llm_judge_score","question","gold","pred_core"]].head(10))

OUT = ROOT / "evaluation" / "eval_results_test_questions_2.csv"
df.to_csv(OUT, index=False, encoding="utf-8-sig")

OUT = ROOT / "evaluation" / "eval_results_test_questions_2_llm_judge.csv"
df_llm_judge.to_csv(OUT, index=False, encoding="utf-8-sig")

print("saved:", OUT)

saved: C:\Users\최무영\Desktop\코드잇 스프린트\Team2-RAG-Project\evaluation\eval_results_test_questions_2_llm_judge.csv

In [22]:
df[["id","correct","score","llm_judge_score","question","gold","pred_core"]]

,id,correct,score,llm_judge_score,question,gold,pred_core
0,1,False,0.326087,None,봉화군에서 진행하는 재난 시스템 고도화 사업 예산이 총 얼마로 잡혀 있나요? 주관 ...,"900,000,000원(VAT 포함)이며, 봉화군 안전건설과에서 주관합니다.","사업금액: 900,000,000원(부가세 포함). 주관부서: 근거 문서에서 확인할 ..."
1,2,True,0.520000,None,이번 봉화군 재난위험지역 경보발령 사업에서 활용하는 무선 통신 방식은 구체적으로 무...,LTE 및 DMB(EWS) 방식을 활용합니다.,LTE 및 DMB(EWS) 기반의 무선방식
2,3,False,0.250000,None,봉화군 재난 사업용 하드웨어 규격 중에서 ECR-02 무선경보장치 스피커의 출력 기...,100W 이상의 출력을 지원해야 합니다.,앰프출력 : 최대 400W 이상(100Wx4ch)
3,4,False,0.340909,None,고려대 차세대 학사시스템 구축 사업의 전체 예산 규모와 연도별 분할 지급 비율이 어...,"총 11,270,000,000원이며, 2024년 30%, 2025년 40%, 202...","전체 예산 11,270,000,000원(부가가치세 포함). 연도별 분할 지급 비율은..."
4,5,False,0.316456,None,고려대 포털 고도화 작업 중에 기존 'AI선배' 서비스의 아키텍처는 어떤 방향으로 ...,Python 기반 모델 아키텍처 고도화 및 서비스 통합 재설계입니다.,- 원데이터 추출·적재방식 및 데이터마트 생성방식을 경영통계시스템과 일원화 \n-...
5,6,True,0.365854,None,고려대 학사행정시스템을 구축할 때 서울과 세종 캠퍼스별 처리에 대한 별도의 지침이 ...,"표준화된 시스템 구축을 원칙으로 하되, 업무 성격상 캠퍼스 구분이 필요한 경우 이를...","네. 표준화된 통합 학사행정시스템을 구축하되, 조회/입력 등 기능 처리 시 서울캠퍼..."
6,7,False,0.125000,None,중앙의료원 응급의료 상황관리시스템 구축 사업에서 광역상황실이 신규로 설치되는 4개 ...,"서울, 대전, 대구, 광주 지역입니다.",근거 문서에서 확인할 수 없습니다
7,8,False,0.074074,None,국립중앙의료원 인프라 요건 중 DB 서버(Server-001)가 갖추어야 할 최소 ...,16 Cores 이상을 요구합니다.,근거 문서에서 확인할 수 없습니다
8,9,False,0.093750,None,응급환자 전원 지원 시스템의 핵심 업무 중 '상황의사'는 주로 어떤 역할을 수행하게...,"의뢰 대상 기관 선정, 수용 의뢰 및 상황 지원을 담당합니다.",근거 문서에서 확인할 수 없습니다
9,10,False,0.235294,None,나노종합기술원의 스마트 팹 설비온라인 시스템 구축 용역은 계약 후 기간이 총 얼마나...,총 18개월입니다.,계약체결일로부터 18개월
10,11,False,0.083333,None,기술원의 'LoT Tracking' 환경 구축을 위해서 구체적으로 어떤 장치나 인터...,Carrier ID 인식 장치 설치 및 정보 표시 인터페이스 구축입니다.,근거 문서에서 확인할 수 없습니다
11,12,False,0.160000,None,나노종합기술원 보안 요건 중에서 DB 암호화 제품이 반드시 획득해야 하는 인증이 무...,CC인증(공통평가기준)이 필수입니다.,검증필 암호모듈 탑재(암호모듈 검증필)
12,13,True,0.575758,None,아시아물위원회에서 추진하는 우즈벡-키르기스스탄 기후대응 관개시스템 사업의 구체적인 ...,키르기즈스탄(Talas-Alatau)과 우즈베키스탄(Ferghana)입니다.,"키르기스스탄: Talas‑Alatau 및 Ferghana 산맥, 우즈베키스탄: Fe..."
13,14,False,0.074074,None,"우즈벡 스마트 관개사업 전문가 파견 시, '수자원 전문가'에게 요구되는 최소 기술 ...",특급 기술자 또는 기술사 자격이 필요합니다.,근거 문서에서 확인할 수 없습니다
14,15,True,0.583333,None,우즈벡-키르기스스탄 현지 지원용 기자재 목록에 포함된 이동 수단은 구체적으로 어떤 ...,SUV 차량 1대입니다.,차량 : SUV 1대
15,16,False,0.085714,None,어촌어항공단 차세대 경영관리시스템 사업에서 그룹웨어(GW)의 주요 개선 목표가 무엇...,사용자 중심의 UI/UX 개선 및 모바일 서비스 강화입니다.,근거 문서에서 확인할 수 없습니다
16,17,False,0.064516,None,공단 사업 지침상 개인정보 보호법을 위반할 경우 매출액 대비 과징금 부과기준율은 어...,"위반 관련 매출액의 1,000분의 21(2.1%)입니다.",근거 문서에서 확인할 수 없습니다
17,18,False,0.105263,None,한국어촌어항공단 사업 수행 인력들의 보안을 위한 비밀유지 서약서는 어느 시점에 제출...,착수계 제출 시 함께 제출해야 합니다.,최종낙찰자 제출
18,19,False,0.103448,None,인천해양박물관 시스템에서 관리하게 될 '해양자료'의 세부 범주에는 어떤 것들이 포함...,"유물, 도서, 기록물 등 박물관 보유 자료 전체입니다.",근거 문서에서 확인할 수 없습니다
19,20,False,0.130435,None,박물관 시스템 보안 약점 중 'Null Pointer 역참조'는 어떤 카테고리로 분...,코드 오류 항목에 해당합니다.,근거 문서에서 확인할 수 없습니다
20,21,False,0.117647,None,인천해양박물관 해양자료관리시스템의 구축 완료 후 하자담보 책임기간은 몇 년인가요?,1년입니다.,검사(검수) 완료 후 1년(12개월)
21,22,False,0.069767,None,벤처확인시스템 고도화 과정에서 '복수의결권주식' 제도를 도입하려는 목적이 무엇인지 ...,비상장 벤처기업 창업자의 경영권 침해 없이 대규모 투자 유치를 지원하기 위함입니다.,근거 문서에서 확인할 수 없습니다
22,23,False,0.320988,None,벤처확인시스템 보안 요구사항 중 SQL 인젝션이나 XSS 방지를 위한 입력 데이터 ...,"SQL 인젝션, 크로스사이트 스크립팅(XSS) 방지 등을 위한 필터링 적용입니다.",프로그램 입력값에 대한 검증 누락 또는 부적절한 검증을 금지(입력데이터 검증 및 표...
23,24,False,0.111111,None,벤처확인종합관리시스템 제안서 평가 항목 중 '수행 조직' 파트에 배정된 배점은 몇 ...,10점입니다.,근거 문서에서 확인할 수 없습니다
24,25,False,0.206897,None,남서울대 학사행정 암호화 사업 추진 배경에 언급된 기존 시스템의 주요 보안 취약점은...,주요 개인정보가 평문으로 저장되어 있어 유출 시 심각한 위협이 됨을 명시하고 있습니다.,기존 시스템에 파일 암호화가 도입되어 있지 않아 원본 첨부파일 유출 시 개인정보 노...
25,26,True,1.000000,None,남서울대 스마트 정보시스템 사업 완료 후 산출되는 결과물들의 지식재산권은 어디에 귀...,남서울대학교에 귀속됩니다.,남서울대학교에 귀속됩니다.
26,27,False,0.168224,None,"남서울대 시스템 활성화 사업 수행 시, 투입 인력들의 대학 내 장소 상주 조건은 어...",사업의 효율적 추진을 위해 대학 내 지정된 장소에 상주함을 원칙으로 합니다.,"투입 인력은 남서울대학교 출입 시 반드시 허가된 지역만 출입해야 하며, 남서울대학교..."
27,28,False,0.100000,None,꿀 등급 판정을 수행하는 현장 인력을 위해 이번에 새롭게 고도화되는 모바일 기능은 ...,태블릿 PC 기반의 모바일 등급판정 시스템 고도화입니다.,품질평가사가 시료채취 후 드럼봉인 시 봉인기에 각인된 드럼관리번호를 관리하기 위한 ...
28,29,False,0.071429,None,꿀 품질평가 사업 보안 지침상 '경미한 위반 3건' 이상 발생 시 어떤 등급의 위약...,D급(200만 원 이하 위약금)입니다.,근거 문서에서 확인할 수 없습니다
29,30,False,0.046512,None,꿀 품질관리 시스템 누출금지 대상정보 중에서 2번 항목에 해당하는 구체적인 정보는 ...,누출금지 대상정보 2번 항목입니다.(세부 정보시스템 구성현황 및 정보통신망 구성도),근거 문서에서 확인할 수 없습니다

In [ ]:
df_llm_judge[["id","correct","score","llm_judge_score","question","gold","pred_core"]]

,id,correct,score,llm_judge_score,question,gold,pred_core
0,1,False,0.304348,None,봉화군에서 진행하는 재난 시스템 고도화 사업 예산이 총 얼마로 잡혀 있나요? 주관 ...,"900,000,000원(VAT 포함)이며, 봉화군 안전건설과에서 주관합니다.","사업금액: 900,000,000원(부가세 포함)\n주관 부서: 근거 문서에서 확인할..."
1,2,False,0.317073,None,이번 봉화군 재난위험지역 경보발령 사업에서 활용하는 무선 통신 방식은 구체적으로 무...,LTE 및 DMB(EWS) 방식을 활용합니다.,"LTE 및 DMB(EWS) 기반 무선방식 (세부: LTE Cat 1, BAND 1/..."
2,3,False,0.173913,None,봉화군 재난 사업용 하드웨어 규격 중에서 ECR-02 무선경보장치 스피커의 출력 기...,100W 이상의 출력을 지원해야 합니다.,앰프출력: 최대 400W 이상(100W x 4ch). 또한 혼스피커는 8Ω/75W ...
3,4,True,0.432432,None,고려대 차세대 학사시스템 구축 사업의 전체 예산 규모와 연도별 분할 지급 비율이 어...,"총 11,270,000,000원이며, 2024년 30%, 2025년 40%, 202...","총 예산 11,270,000,000원(V.A.T 포함). 3년 분할지급: 2024학..."
4,5,False,0.333333,None,고려대 포털 고도화 작업 중에 기존 'AI선배' 서비스의 아키텍처는 어떤 방향으로 ...,Python 기반 모델 아키텍처 고도화 및 서비스 통합 재설계입니다.,기존 AI선배는\n- 경영통계시스템과 원데이터 추출·적재방식 및 데이터마트 생성방식...
5,6,False,0.319149,None,고려대 학사행정시스템을 구축할 때 서울과 세종 캠퍼스별 처리에 대한 별도의 지침이 ...,"표준화된 시스템 구축을 원칙으로 하되, 업무 성격상 캠퍼스 구분이 필요한 경우 이를...","예. 표준화된 통합 학사행정시스템으로 구현하되, 조회/입력 등 기능 처리 시 서울캠..."
6,7,False,0.125000,None,중앙의료원 응급의료 상황관리시스템 구축 사업에서 광역상황실이 신규로 설치되는 4개 ...,"서울, 대전, 대구, 광주 지역입니다.",근거 문서에서 확인할 수 없습니다
7,8,False,0.074074,None,국립중앙의료원 인프라 요건 중 DB 서버(Server-001)가 갖추어야 할 최소 ...,16 Cores 이상을 요구합니다.,근거 문서에서 확인할 수 없습니다
8,9,False,0.093750,None,응급환자 전원 지원 시스템의 핵심 업무 중 '상황의사'는 주로 어떤 역할을 수행하게...,"의뢰 대상 기관 선정, 수용 의뢰 및 상황 지원을 담당합니다.",근거 문서에서 확인할 수 없습니다
9,10,False,0.235294,None,나노종합기술원의 스마트 팹 설비온라인 시스템 구축 용역은 계약 후 기간이 총 얼마나...,총 18개월입니다.,계약체결일로부터 18개월
10,11,False,0.083333,None,기술원의 'LoT Tracking' 환경 구축을 위해서 구체적으로 어떤 장치나 인터...,Carrier ID 인식 장치 설치 및 정보 표시 인터페이스 구축입니다.,근거 문서에서 확인할 수 없습니다
11,12,False,0.080000,None,나노종합기술원 보안 요건 중에서 DB 암호화 제품이 반드시 획득해야 하는 인증이 무...,CC인증(공통평가기준)이 필수입니다.,검증필 암호모듈 탑재
12,13,True,0.709677,None,아시아물위원회에서 추진하는 우즈벡-키르기스스탄 기후대응 관개시스템 사업의 구체적인 ...,키르기즈스탄(Talas-Alatau)과 우즈베키스탄(Ferghana)입니다.,"키르기스스탄(Talas-Alatau 및 Ferghana 산맥), 우즈베키스탄(Fer..."
13,14,False,0.074074,None,"우즈벡 스마트 관개사업 전문가 파견 시, '수자원 전문가'에게 요구되는 최소 기술 ...",특급 기술자 또는 기술사 자격이 필요합니다.,근거 문서에서 확인할 수 없습니다
14,15,True,0.454545,None,우즈벡-키르기스스탄 현지 지원용 기자재 목록에 포함된 이동 수단은 구체적으로 어떤 ...,SUV 차량 1대입니다.,SUV 1대
15,16,False,0.085714,None,어촌어항공단 차세대 경영관리시스템 사업에서 그룹웨어(GW)의 주요 개선 목표가 무엇...,사용자 중심의 UI/UX 개선 및 모바일 서비스 강화입니다.,근거 문서에서 확인할 수 없습니다
16,17,False,0.064516,None,공단 사업 지침상 개인정보 보호법을 위반할 경우 매출액 대비 과징금 부과기준율은 어...,"위반 관련 매출액의 1,000분의 21(2.1%)입니다.",근거 문서에서 확인할 수 없습니다
17,18,True,0.687500,None,한국어촌어항공단 사업 수행 인력들의 보안을 위한 비밀유지 서약서는 어느 시점에 제출...,착수계 제출 시 함께 제출해야 합니다.,사업 착수 시 제출해야 합니다.
18,19,False,0.103448,None,인천해양박물관 시스템에서 관리하게 될 '해양자료'의 세부 범주에는 어떤 것들이 포함...,"유물, 도서, 기록물 등 박물관 보유 자료 전체입니다.",근거 문서에서 확인할 수 없습니다
19,20,False,0.130435,None,박물관 시스템 보안 약점 중 'Null Pointer 역참조'는 어떤 카테고리로 분...,코드 오류 항목에 해당합니다.,근거 문서에서 확인할 수 없습니다
20,21,False,0.105263,None,인천해양박물관 해양자료관리시스템의 구축 완료 후 하자담보 책임기간은 몇 년인가요?,1년입니다.,1년(검수완료일로부터 12개월)
21,22,False,0.069767,None,벤처확인시스템 고도화 과정에서 '복수의결권주식' 제도를 도입하려는 목적이 무엇인지 ...,비상장 벤처기업 창업자의 경영권 침해 없이 대규모 투자 유치를 지원하기 위함입니다.,근거 문서에서 확인할 수 없습니다
22,23,False,0.178947,None,벤처확인시스템 보안 요구사항 중 SQL 인젝션이나 XSS 방지를 위한 입력 데이터 ...,"SQL 인젝션, 크로스사이트 스크립팅(XSS) 방지 등을 위한 필터링 적용입니다.","입력데이터 검증은 ""입력값에 대한 검증 누락 또는 부적절한 검증, 데이터의 잘못된 ..."
23,24,False,0.111111,None,벤처확인종합관리시스템 제안서 평가 항목 중 '수행 조직' 파트에 배정된 배점은 몇 ...,10점입니다.,근거 문서에서 확인할 수 없습니다
24,25,False,0.202247,None,남서울대 학사행정 암호화 사업 추진 배경에 언급된 기존 시스템의 주요 보안 취약점은...,주요 개인정보가 평문으로 저장되어 있어 유출 시 심각한 위협이 됨을 명시하고 있습니다.,기존에 파일 암호화가 도입되어 있지 않아 원본 파일 유출 시 개인정보가 노출되어 큰...
25,26,True,1.000000,None,남서울대 스마트 정보시스템 사업 완료 후 산출되는 결과물들의 지식재산권은 어디에 귀...,남서울대학교에 귀속됩니다.,"남서울대학교에 귀속됩니다. (사업수행 중 산출된 서적, 컴퓨터 프로그램, 장치, 기..."
26,27,False,0.171429,None,"남서울대 시스템 활성화 사업 수행 시, 투입 인력들의 대학 내 장소 상주 조건은 어...",사업의 효율적 추진을 위해 대학 내 지정된 장소에 상주함을 원칙으로 합니다.,투입 인력은 남서울대학교 출입 시 반드시 허가된 지역만 출입해야 하며(보안관리 규정...
27,28,False,0.120000,None,꿀 등급 판정을 수행하는 현장 인력을 위해 이번에 새롭게 고도화되는 모바일 기능은 ...,태블릿 PC 기반의 모바일 등급판정 시스템 고도화입니다.,품질평가사가 시료채취 후 드럼봉인 시 봉인기에 각인된 드럼관리번호를 관리하는 기능 ...
28,29,False,0.071429,None,꿀 품질평가 사업 보안 지침상 '경미한 위반 3건' 이상 발생 시 어떤 등급의 위약...,D급(200만 원 이하 위약금)입니다.,근거 문서에서 확인할 수 없습니다
29,30,False,0.046512,None,꿀 품질관리 시스템 누출금지 대상정보 중에서 2번 항목에 해당하는 구체적인 정보는 ...,누출금지 대상정보 2번 항목입니다.(세부 정보시스템 구성현황 및 정보통신망 구성도),근거 문서에서 확인할 수 없습니다